package com.example.gov_scheme_backend.services.impl;

import java.util.ArrayList;
import java.util.List;
import java.util.Set;
import java.util.UUID;
import java.util.stream.Collectors;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.web.multipart.MultipartFile;

import com.example.gov_scheme_backend.dto.request.application.ApplicationFieldValueRequestDTO;
import com.example.gov_scheme_backend.dto.request.application.FieldValueRequestDTO;
import com.example.gov_scheme_backend.dto.response.application.EligibilityEngineScoreDTO;
import com.example.gov_scheme_backend.entities.Application;
import com.example.gov_scheme_backend.entities.ApplicationDocument;
import com.example.gov_scheme_backend.entities.ApplicationFieldValue;
import com.example.gov_scheme_backend.entities.Schemes;
import com.example.gov_scheme_backend.entities.Users;
import com.example.gov_scheme_backend.enums.ApplicationStatus;
import com.example.gov_scheme_backend.enums.DocumentType;
import com.example.gov_scheme_backend.exceptions.BadRequestException;
import com.example.gov_scheme_backend.exceptions.DuplicateResourceException;
import com.example.gov_scheme_backend.exceptions.ResourceNotFoundException;
import com.example.gov_scheme_backend.repositories.ApplicationRepo;
import com.example.gov_scheme_backend.repositories.SchemeRepo;
import com.example.gov_scheme_backend.repositories.UserRepo;
import com.example.gov_scheme_backend.services.ApplicationService;
import com.example.gov_scheme_backend.services.CloudinaryService;
import com.example.gov_scheme_backend.services.EligibilityEngineService;
import com.example.gov_scheme_backend.services.WorkflowService;

import jakarta.transaction.Transactional;
import lombok.RequiredArgsConstructor;

@Service
@RequiredArgsConstructor
public class ApplicationServiceImpl implements ApplicationService {

    @Autowired
    ApplicationRepo applicationRepo;

    @Autowired
    UserRepo userRepo;

    @Autowired
    SchemeRepo schemeRepo;

    @Autowired
    EligibilityEngineService check;

    @Autowired
    private com.example.gov_scheme_backend.repositories.AuditLogRepo auditLogRepo;

    @Autowired
    WorkflowService workflowService;

    // Injected via constructor by Spring (generated by @RequiredArgsConstructor)
    // CloudinaryService handles all Cloudinary SDK interactions
    private final CloudinaryService cloudinaryService;

    @Override
    @Transactional
    public EligibilityEngineScoreDTO saveFields(
            Long userId,
            ApplicationFieldValueRequestDTO req) {

        if (req == null
                || req.getSchemeCode() == null
                || req.getSchemeCode().trim().isEmpty()) {

            throw new BadRequestException("Scheme code is required");
        }

        Users user = userRepo.findById(userId)
                .orElseThrow(() ->
                        new ResourceNotFoundException("User not found"));

        Schemes scheme = schemeRepo.findBySchemeCode(req.getSchemeCode().trim())
                .orElseThrow(() ->
                        new ResourceNotFoundException(
                                "Scheme not found with code: "
                                        + req.getSchemeCode()));

        Application app = applicationRepo
                .findByUser_IdAndScheme_SchemeCode(
                        userId,
                        scheme.getSchemeCode())
                .map(existingApplication -> {

                    if (existingApplication.getStatus() != null
                            && existingApplication.getStatus()
                            != ApplicationStatus.DRAFT
                            && existingApplication.getStatus()
                            != ApplicationStatus.PENDING) {

                        throw new DuplicateResourceException(
                                "An application already exists for this scheme. "
                                        + "Please continue or cancel the existing application."
                        );
                    }

                    if (existingApplication.getFieldValues() != null) {
                        existingApplication.getFieldValues().clear();
                    }

                    if (existingApplication.getDocuments() != null) {
                        existingApplication.getDocuments().clear();
                    }

                    existingApplication.setStatus(ApplicationStatus.DRAFT);

                    return existingApplication;
                })
                .orElseGet(() -> {

                    Application newApplication = new Application();

                    newApplication.setApplicationCode(
                            "APP-"
                                    + UUID.randomUUID()
                                    .toString()
                                    .substring(0, 8)
                                    .toUpperCase()
                    );

                    newApplication.setUser(user);
                    newApplication.setScheme(scheme);
                    newApplication.setStatus(ApplicationStatus.DRAFT);

                    return newApplication;
                });

        List<FieldValueRequestDTO> submittedFields =
                req.getFields() == null
                        ? List.of()
                        : req.getFields();

                // Preserve Hibernate-managed collection
        if (app.getFieldValues() == null) {
           app.setFieldValues(new ArrayList<>());
        } else {
           app.getFieldValues().clear();
        }

        for (FieldValueRequestDTO dto : submittedFields) {

            if (dto == null || dto.getFieldName() == null) {
                continue;
             }

            ApplicationFieldValue field = new ApplicationFieldValue();

            field.setFieldName(dto.getFieldName());
            field.setFieldValue(dto.getValue());
            field.setApplication(app);

            app.getFieldValues().add(field);
        }

        Application saved = applicationRepo.save(app);

        /*
         * Before running the eligibility engine, make sure all
         * required eligibility fields have been provided.
         */
        String missingField =
                findMissingEligibilityField(
                        scheme,
                        submittedFields);

        if (missingField != null) {

            return new EligibilityEngineScoreDTO(
                    false,
                    0.0,
                    0.0,
                    "Missing value for field: " + missingField,
                    new java.util.ArrayList<>()
            );
        }

        /*
         * Run eligibility engine after all required fields
         * have been supplied.
         */
        EligibilityEngineScoreDTO result = check.validateFields(saved.getId());

        boolean passed;
        if (result.getTotalPossibleScore() <= 0) {
            // No rules have point values configured — treat as a checklist:
            // eligible only if every evaluated rule was individually met.
            passed = result.getFieldBreakdown() != null
                    && !result.getFieldBreakdown().isEmpty()
                    && result.getFieldBreakdown().stream().allMatch(
                            com.example.gov_scheme_backend.dto.response.application.EligibilityFieldResultDTO::isRuleMet);
        } else {
            double minScore = scheme.getMinimumEligibleScore() != null ? scheme.getMinimumEligibleScore() : 0.0;
            // If the configured threshold exceeds what the rules can possibly award,
            // cap it at totalPossibleScore — otherwise a user who passes every rule
            // would still be marked ineligible due to a misconfigured threshold.
            double effectiveThreshold = Math.min(minScore, result.getTotalPossibleScore());
            passed = result.getScore() >= effectiveThreshold;
        }

        if (!passed) {
            result.setStatus(false);
            result.setMessage("You are not eligible");
            return result;
        }

        /*
         * Applicant passed the eligibility check.
         * Keep the application pending until the beneficiary
         * explicitly submits it.
         */
        app.setStatus(ApplicationStatus.PENDING);

        applicationRepo.save(app);

        result.setStatus(true);
        result.setMessage("You are eligible");
        return result;
    }

    @Override
    @Transactional
    public void cancelApplication(
            Long userId,
            Long applicationId) {

        if (applicationId == null) {
            throw new BadRequestException(
                    "Application ID is required");
        }

        Application application = applicationRepo
                .findById(applicationId)
                .orElseThrow(() ->
                        new ResourceNotFoundException(
                                "No application found for this application ID"));

        if (application.getUser() == null
                || application.getUser().getId() == null
                || !application.getUser()
                .getId()
                .equals(userId)) {

            throw new BadRequestException(
                    "You are not allowed to cancel this application");
        }

        if (application.getStatus() != ApplicationStatus.DRAFT
                && application.getStatus() != ApplicationStatus.PENDING) {

            throw new BadRequestException(
                    "Only draft applications can be cancelled");
        }

        applicationRepo.delete(application);

        com.example.gov_scheme_backend.entities.AuditLog audit = com.example.gov_scheme_backend.entities.AuditLog.builder()
                .auditId(UUID.randomUUID().toString())
                .user(application.getUser())
                .action(com.example.gov_scheme_backend.enums.AuditAction.DELETE)
                .description("Cancelled application ID: " + applicationId)
                .build();
        auditLogRepo.save(audit);
    }

    @Override
    @Transactional
    public void submitApplication(
            Long userId,
            String schemeCode) {

        if (schemeCode == null
                || schemeCode.trim().isEmpty()) {

            throw new BadRequestException(
                    "Scheme code is required");
        }

        Application application =
                applicationRepo
                        .findByUser_IdAndScheme_SchemeCode(
                                userId,
                                schemeCode.trim())
                        .orElseThrow(() ->
                                new ResourceNotFoundException(
                                        "No application found for this scheme"));

        if (application.getStatus() != ApplicationStatus.DRAFT
                && application.getStatus() != ApplicationStatus.PENDING) {

            throw new BadRequestException(
                    "Application has already been submitted");
        }

        application.setStatus(ApplicationStatus.SUBMITTED);

        applicationRepo.save(application);

        // Start the staged officer workflow only after the beneficiary submits.
        workflowService.createWorkflow(application);

        com.example.gov_scheme_backend.entities.AuditLog audit = com.example.gov_scheme_backend.entities.AuditLog.builder()
                .auditId(UUID.randomUUID().toString())
                .user(application.getUser())
                .action(com.example.gov_scheme_backend.enums.AuditAction.UPDATE)
                .description("Submitted application for scheme: " + schemeCode)
                .build();
        auditLogRepo.save(audit);
    }

    private String findMissingEligibilityField(
            Schemes scheme,
            List<FieldValueRequestDTO> submittedFields) {

        if (scheme == null
                || scheme.getEligibilityRules() == null
                || scheme.getEligibilityRules().isEmpty()) {

            return null;
        }

        Set<String> providedFields =
                submittedFields.stream()
                        .filter(dto ->
                                dto != null
                                        && dto.getFieldName() != null)
                        .map(dto ->
                                dto.getFieldName().name())
                        .collect(Collectors.toSet());

        for (var rule : scheme.getEligibilityRules()) {

            if (rule == null
                    || rule.getFieldName() == null) {

                continue;
            }

            if (!providedFields.contains(
                    rule.getFieldName().name())) {

                return rule.getFieldName().name();
            }
        }

        return null;
    }

    // -------------------------------------------------------------------------
    // Document Upload
    // -------------------------------------------------------------------------

    @Override
    @Transactional
    public void uploadDocuments(
            Long userId,
            String schemeCode,
            List<MultipartFile> files,
            List<DocumentType> documentTypes) {

        if (schemeCode == null || schemeCode.trim().isEmpty()) {
            throw new BadRequestException("Scheme code is required");
        }

        if (files == null || files.isEmpty()) {
            throw new BadRequestException("At least one document file is required");
        }

        if (documentTypes == null || documentTypes.size() != files.size()) {
            throw new BadRequestException(
                    "Number of document types must match number of files. " +
                    "Got " + (documentTypes == null ? 0 : documentTypes.size()) +
                    " types for " + files.size() + " files"
            );
        }

        // Look up the existing application for this user+scheme
        Application application = applicationRepo
                .findByUser_IdAndScheme_SchemeCode(userId, schemeCode.trim())
                .orElseThrow(() -> new ResourceNotFoundException(
                        "No application found for scheme '" + schemeCode +
                        "'. Please save your fields first."));

        // Only allow document upload for applications that are still in draft,
        // eligible-but-not-submitted, or already in the officer review flow.
        ApplicationStatus status = application.getStatus();
        if (status != ApplicationStatus.DRAFT
                && status != ApplicationStatus.PENDING
                && status != ApplicationStatus.UNDER_REVIEW) {
            throw new BadRequestException(
                    "Documents can only be uploaded for applications in DRAFT, PENDING or UNDER_REVIEW status. " +
                    "Current status: " + status);
        }

        // Build the new list of ApplicationDocument entities.
        // Each file is uploaded to Cloudinary individually.
        // If ANY upload fails, the entire transaction is rolled back.
        List<ApplicationDocument> newDocuments = new ArrayList<>();

        for (int i = 0; i < files.size(); i++) {
            MultipartFile file = files.get(i);
            DocumentType docType = documentTypes.get(i);

            // Upload to Cloudinary — CloudinaryServiceImpl validates type & size
            String secureUrl = cloudinaryService.uploadFile(file, "govt-scheme-docs");

            // Guard: do NOT persist if URL is missing
            if (secureUrl == null || secureUrl.isBlank()) {
                throw new RuntimeException(
                        "Cloudinary returned an empty URL for file: " +
                        file.getOriginalFilename() + ". Aborting document save.");
            }

            ApplicationDocument doc = new ApplicationDocument();
            doc.setApplication(application);
            doc.setDocumentType(docType);
            doc.setFileName(
                    file.getOriginalFilename() != null
                            ? file.getOriginalFilename()
                            : "document_" + i);
            // filePath is kept for backward compatibility — set to empty string
            // (not null, since the column is nullable=false in the entity)
            doc.setFilePath("");
            doc.setVerified(false);
            doc.setDocumentUrl(secureUrl);  // <-- Cloudinary secure_url stored here

            newDocuments.add(doc);
        }


                // Preserve Hibernate-managed documents collection.
        // Do NOT replace the collection reference because
        // orphanRemoval = true on Application.documents.
        if (application.getDocuments() == null) {
                application.setDocuments(new ArrayList<>());
        } else {
                application.getDocuments().clear();
        }

        application.getDocuments().addAll(newDocuments);

        applicationRepo.save(application);
        
    }
}
